services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"  # Expose the port defined in the .env file
    volumes:
      - /Users/belletheere/Desktop/Seniorproject/coding/backend  # Map the current directory to the container
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

 
